version: "3.7"
services:
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  caoq:
    image: frenetiq/caoq:bleeding
    ports:
      - "5672:5672"
