FROM rust:latest AS deps

WORKDIR /caolo
RUN cargo install sqlx-cli --version=0.1.0-beta.1 --no-default-features --features=postgres,runtime-async-std-native-tls --root .

FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install libpq-dev -y

COPY ./migrations ./migrations
COPY --from=deps /caolo/bin/sqlx ./sqlx

ENTRYPOINT ["./sqlx", "migrate", "run"]
