version: "3.7"
services:
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  redis:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
